<?php

require_once __DIR__."/../libs/functions.php";

// Load Nette Framework or autoloader generated by Composer
require __DIR__ . '/../libs/autoload.php';

use Nette\Application\Routers\RouteList,
    Nette\Application\Routers\Route;

define("ROOT", __DIR__."/../");

$configurator = new Nette\Config\Configurator;

// Enable Nette Debugger for error visualisation & logging
$configurator->setDebugMode(true);
ob_start(); //Because of firelogger only debug

$configurator->enableDebugger(__DIR__ . '/../log');
// Enable RobotLoader - this will load all classes automatically
$configurator->setTempDirectory(__DIR__ . '/../temp');
$configurator->createRobotLoader()
	->addDirectory(__DIR__ . '/../_admin')
	->addDirectory(__DIR__ . '/../_public')
	->addDirectory(__DIR__)
	->addDirectory(__DIR__ . '/../libs')
        ->addDirectory(__DIR__ . '/../plugins')
	->addDirectory(__DIR__ . '/../nblocks')
	->addDirectory(__DIR__ . '/../models')
	->addDirectory(__DIR__ . '/../mylibs')
	->register();

// Create Dependency Injection container from config.neon file
$configurator->addConfig(__DIR__ . '/../config/config.neon');
$configurator->addConfig(__DIR__ . '/../config/config.local.neon', $configurator::NONE); // none section


$container = $configurator->createContainer();
Kdyby\Replicator\Container::register();
$router = new RouteList;
//$router[] = new Route('article/<id>', 'Article:view');
//$router[] = new Route('rss.xml', 'Feed:rss');
$router[] = new Route('index.php', 'Front:Homepage:default');
$router[] = new Route('<presenter>/<action>[/<id>]', 'Front:Homepage:default');

$container->addService('router', $router);




return $container;
